

# tasks file for etcd
- name: Install the etcd
  yum: name="etcd" state=latest update_cache=yes


- template:
    src: templates/etcd.service.j2
    dest: /usr/lib/systemd/system/etcd.service
    mode: 0755
  name: generating the etcd.service file

- name: Create data directory for etcd
  file:  
    path: "{{etcd.dir}}"
    owner: etcd
    group: etcd
    mode: 0744  
    state: directory

 
- name: open etcd ports on iptables --incoming
  shell: /usr/sbin/iptables -A INPUT -m state --state NEW -p tcp --dport {{item}} -j ACCEPT
  loop:
    - "{{ etcd.ports.client }}"
    - "{{ etcd.ports.peer }}"

- name: Enable and start the etcd
  systemd:
    name: etcd
    state: started
    enabled: True 

- pause:
    minutes: 1
  name: wait till the etcd cluster assemble

  
