---
# tasks file for common
- template:
    src: templates/hosts.j2
    dest: /root/hosts
    mode: 0755

- template:
    src: templates/docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo
    mode: 0755

- template:
    src: templates/k8.repo.j2
    dest: /etc/yum.repos.d/k8.repo
    mode: 0755    

#- name:  Update host mapping in all the nodes
#  shell:  cat /root/hosts >> /etc/hosts

- name: Install the docker/kubernetes software
  yum: name="{{ item }}" state=latest update_cache=yes
  loop:
    - docker-ce
    - kubeadm
    
- name:  Disable SE linux in /etc/selinux/config 
  replace:
    path: /etc/selinux/config
    regexp: 'SELINUX=enforcing'
    #replace: 'SELINUX=disabled'
    replace: 'SELINUX=permissive'
    backup: yes

- name:  Disable swap. Running with swap on is nok for kubernetes 
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '#\1'
    backup: yes


- name:  Make sysctl changes permanent
  shell:  sysctl -a > /etc/sysctl.conf
    
- name:  Enable iptable processing
  lineinfile:
    path: /etc/sysctl.conf
    insertafter: EOF
    line: 'net.bridge.bridge-nf-call-iptables=1'  

- name:  Enable ip forwarding
  replace:
    path: /etc/sysctl.conf
    regexp: 'net.ipv4.ip_forward *= *0'
    replace: 'net.ipv4.ip_forward=1'
    backup: yes


- name: Enable and start the daemons-docker
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True    
  loop:
    - docker

- name: Enable the daemons-kubelet
  systemd:
    name: "{{ item }}"
    enabled: True    
  loop:
    - kubelet    


- name:  Reboot the node
  shell:  reboot
  