---
# tasks file for kube

- name: Init the kubeadm
  shell: kubeadm init --apiserver-advertise-address="{{inventory_hostname}}" --pod-network-cidr=10.244.0.0/16
  #shell: kubeadm init --apiserver-advertise-address="{{inventory_hostname}}"

- name: Configure kubelet config - create $HOME/.kube
  shell: mkdir -p $HOME/.kube

- name: Configure kubelet config - copy /etc/kubernetes/admin.conf to create $HOME/.kube
  shell: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

- name: configure flannel 3rd party network
  #shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
  #shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: update the coredns: allowPrivilegeEscalation
  shell: kubectl -n kube-system get deployment coredns -o yaml | sed 's/allowPrivilegeEscalation: false/allowPrivilegeEscalation: true/g' | kubectl apply -f -

- name: Get the cluster join command
  shell: kubeadm token create --print-join-command
  register: workerInitCmd 
    
- name: Join the workers to kube cluster
  shell: "{{workerInitCmd.stdout}}"
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['worker']}}"  


